spring.application.name=PeopleHub

spring.config.import=optional:file:dev-env.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/public_hub
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
WEBSITE_BASEURL=${BASEURL}
REFRESH_TOKEN_EXPIRY=1296000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SENDER_EMAIL}
spring.mail.password=${SENDER_EMAIL_PASSWORD}

logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG